[package]
name = "verlet-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = { version = "5.5.0", features = [] }
cgmath = "0.18.0"
rayon = "1.5.1"
clap = { version = "4.5.49", features = ["derive"] }
